### ISSUE TITLE
lodash functions don't quite seem to work inside lambdas

### ISSUE THREAD

**Issue by jedwards1211** [FGRibreau/jq.node#11]
This is awesome and less confusing to me than `jq`, but I still find it a bit confusing.
```
$ curl 'https://api.github.com/repos/stedolan/jq/commits?per_page=5' | jqn 'map(u => pick(u, "sha"))'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18379  100 18379    0     0  20034      0 --:--:-- --:--:-- --:--:-- 20020
[
  {},
  {},
  {},
  {},
  {}
]
```

I discovered that `jqn 'map(pick("sha"))'` works, but you know what would have been most stupid-simple obvious to me? A lambda that takes the JSON as input.  Definitely not as elegant, but impossible for an experienced JS developer to screw up:
```
$ curl ... | jqn 'j => map(j, u => pick(u, "sha"))'
```

**Comment by FGRibreau** [comment]
It's because you might want to take a look at [lodash/fp](https://github.com/lodash/lodash/wiki/FP-Guide):

> The lodash/fp module promotes a more functional programming (FP) friendly style by exporting an instance of lodash with its methods wrapped to produce immutable auto-curried iteratee-first data-last methods.

Once you get it, you won't be able to live without it, definitely less verbose than lodash and more reusable (because it's more FP oriented)

**Comment by jedwards1211** [comment]
@FGRibreau oh, gotcha!
