### ISSUE TITLE
Implement NodeJS API

### ISSUE THREAD

**Issue by antony** [FGRibreau/jq.node#14]
Hi.

Love the module! The only thing which appears to be missing is a way of using this from node itself, i.e:

```js
const jq = require('jq.node')
jq('.version')
```

Is this planned? possible?

**Comment by FGRibreau** [comment]
Hello @antony,

Why would you want to use it as a library?

**Comment by antony** [comment]
Hi @FGRibreau,

I use `jq.node` as a data transformation method in my dashboard software.

You can see how I currently use it here:

https://github.com/vudash/vudash/blob/master/packages/transformer-jq/transformer.js

Obviously piping the output to and from a child process isn't optimal, and is considerably heavier than I would like it to be!

**Comment by FGRibreau** [comment]
@antony ok indeed, you know what? Just send a PR and we will discuss the API over it :)

**Comment by antony** [comment]
Will do so as soon as I have an opportunity!

**Comment by FGRibreau** [comment]
merged #15
