### ISSUE TITLE
Arguments not compatible with jq

### ISSUE THREAD

**Issue by huan** [FGRibreau/jq.node#19]
### `jq`

I can run `jq .version package.json` to print the version number from a package.json.

```shell
$ jq .version package.json 
"0.1.7"
```

And I can edit it:

```shell
$ jq '.version="1.0.0"' package.json
```

### `node.jq`

however, this is invalid when I use jq.node:

Not this:

```shell
$ ./node_modules/.bin/jq.node .version package.json 
Usage: jq.node <command> [options]

Options:
  -h, --help       Show help  [boolean]
  -v, --version    Show version number  [boolean]
  -x, --raw-input  Read input as a string  [boolean]
  -j, --json       Force JSON output  [boolean]
  -C, --color      Colorize JSON (--color=false to disable it)  [boolean] [default: true]
  -r, --require    require the given module
```

Not that:

```shell
$ cat package.json | ./node_modules/.bin/jq.node .version 
evalmachine.<anonymous>:1
flow(.version)($$input$$);
     ^

SyntaxError: Unexpected token.
    at new Script (vm.js:79:7)
    at Socket.<anonymous> (/home/huan/git/pkg-jq/node_modules/jq.node/lib/core.js:47:20)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I have to do it the jq.node style:

```shell
$ cat package.json | ./node_modules/.bin/jq.node 'get("version")'
0.1.7
```

### The Question

My question is: could we compatible with the `jq` parameters in the future? Or we designed to not do that at all?

Thanks.

**Comment by FGRibreau** [comment]
> My question is: could we compatible with the jq parameters in the future? Or we designed to not do that at all?

Indeed, it was not designed to do that at all. Instead it relies on JavaScript, please read [this part from README](https://github.com/FGRibreau/jq.node#why-jqnode-why-not-jq).

**Comment by huan** [comment]
Got it. So the name is a little bit confusing.

Thanks for your reply, have a nice day!
