### ISSUE TITLE
Change default color behaviour

### ISSUE THREAD

**Issue by jayeheffernan** [FGRibreau/jq.node#47]
Hi there, awesome library!  Much more intuitive than `jq` for a JS developer like myself.  I have a feature request to make it a bit more convenient/intuitive still.

I think that the default behaviour of the color options should be changed.  You have mentioned this yourself [here](https://github.com/FGRibreau/jq.node/issues/18#issuecomment-446750075).  The colorized output can be annoying when using `jq.node` as part of a pipeline in scripts.  Personally, my main use case is for filtering JSON data that I'm editing in Vim, and the color codes get in my way each time I try to do this (until I figure out again what option I need to use).

The best option would be to use something like [supports-color](https://github.com/chalk/supports-color) to guess whether the output should be colorized (but if an explicit option value is given it should override this guess).  [colors.js](https://github.com/Marak/colors.js) and [chalk](https://github.com/chalk/chalk) both work this way, for example.  This way it can automatically handle adding nice colors for an interactive terminal session, and omitting them in a script or pipeline.

Thanks!

**Comment by FGRibreau** [comment]
Indeed, I agree, please open a PR along with some tests and I will merge it :+1:
