### ISSUE TITLE
Allow installing alongside jq

### ISSUE THREAD

**Issue by timwis** [FGRibreau/jq.node#8]
I just installed `jq.node` and it made it so I can't use `jq` anymore. It would be great if there were a way to install it without using the `jq` namespace (i'm fine writing `jq.node` to use this one).

**Comment by FGRibreau** [comment]
It's not supported currently, see https://github.com/FGRibreau/jq.node/issues/1

**Comment by timwis** [comment]
Hm, may I ask what the advantage is of calling this `jq` at all? Is there any parity with `jq`? Why not just give this utility a different name, and call it a more powerful alternative to `jq`? That way users could have both utilities installed at the same time.

**Comment by FGRibreau** [comment]
We could indeed, do you have any names in mind @timwis?
