### ISSUE TITLE
Rename binary to `jqn`

### ISSUE THREAD

**Issue by thalesmello** [FGRibreau/jq.node#9]
I love the concept of this project, but the binary installed has a conflict with the current `jq` binary.

In order to avoid that, I would like to suggest changing the binary of this program to `jqn`. I particularly want to be able to choose when I want to use the old jq or this one.

**Comment by thalesmello** [comment]
Any comments on this? @FGRibreau

**Comment by FGRibreau** [comment]
@thalesmello please submit a PR for it :)

**Comment by FGRibreau** [comment]
Done https://github.com/FGRibreau/jq.node/pull/10
